<h3 style="margin:0px">Class: org.jclouds.util.Throwables2Test (17 methods) </h3><br><pre style="padding:0"><code class="html"><div id="tags"><button id="10"style="border-width:0;padding:0;background:#282B2E"  onclick="filter('10')" data-toggle="tooltip" title="Executes methods or other tests from the same test unit"><kbd id="tag-10"class="label-info"style="display: inline-block;font-size:7pt" >ExecutionTester&nbsp;(17)</kbd></button>&nbsp;<button id="3"style="border-width:0;padding:0;background:#282B2E"  onclick="filter('3')" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution"><kbd id="tag-3"class="label-info"style="display: inline-block;font-size:7pt" >ExceptionVerifier&nbsp;(16)</kbd></button>&nbsp;</div></code></pre><center><button onclick="showBlocks()" style="margin:6px">Update filter <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span> </button></center><br>
<pre class="type-3 type-10 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Executes methods or other tests from the same test unit">ExecutionTester</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
- Executes methods or other tests from the same test unit
"></span><br>
@Test(expectedExceptions=AuthorizationException.class) public void testPropagateStandardExceptionAuthorizationException() throws Throwable {
  Exception e=new AuthorizationException();
  propagateIfPossible(new RuntimeException(e),ImmutableSet.<TypeToken<? extends Throwable>>of());
}

</code></pre>

<pre class="type-3 type-10 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Executes methods or other tests from the same test unit">ExecutionTester</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
- Executes methods or other tests from the same test unit
"></span><br>
@Test(expectedExceptions=AuthorizationException.class) public void testPropagateProvisionExceptionAuthorizationException() throws Throwable {
  Exception e=new AuthorizationException();
  propagateIfPossible(new ProvisionException(ImmutableSet.of(new Message(ImmutableList.of(),"Error in custom provider",e))),ImmutableSet.<TypeToken<? extends Throwable>>of());
}

</code></pre>

<pre class="type-3 type-10 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Executes methods or other tests from the same test unit">ExecutionTester</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
- Executes methods or other tests from the same test unit
"></span><br>
@Test(expectedExceptions=InsufficientResourcesException.class) public void testPropagateStandardExceptionInsufficientResourcesException() throws Throwable {
  Exception e=new InsufficientResourcesException();
  propagateIfPossible(new RuntimeException(e),ImmutableSet.<TypeToken<? extends Throwable>>of());
}

</code></pre>

<pre class="type-3 type-10 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Executes methods or other tests from the same test unit">ExecutionTester</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
- Executes methods or other tests from the same test unit
"></span><br>
@Test(expectedExceptions=ResourceNotFoundException.class) public void testPropagateStandardExceptionResourceNotFoundExceptionNestedInHttpResponseException() throws Throwable {
  Exception e=new ResourceNotFoundException();
  propagateIfPossible(new HttpResponseException("goo",createNiceMock(HttpCommand.class),null,e),ImmutableSet.<TypeToken<? extends Throwable>>of());
}

</code></pre>

<pre class="type-3 type-10 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Executes methods or other tests from the same test unit">ExecutionTester</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
- Executes methods or other tests from the same test unit
"></span><br>
@Test(expectedExceptions=AuthorizationException.class) public void testPropagateStandardExceptionAuthorizationExceptionNestedInHttpResponseException() throws Throwable {
  Exception e=new AuthorizationException();
  propagateIfPossible(new HttpResponseException("goo",createNiceMock(HttpCommand.class),null,e),ImmutableSet.<TypeToken<? extends Throwable>>of());
}

</code></pre>

<pre class="type-3 type-10 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Executes methods or other tests from the same test unit">ExecutionTester</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
- Executes methods or other tests from the same test unit
"></span><br>
@Test(expectedExceptions=UnsupportedOperationException.class) public void testPropagateStandardExceptionUnsupportedOperationException() throws Throwable {
  Exception e=new UnsupportedOperationException();
  propagateIfPossible(new RuntimeException(e),ImmutableSet.<TypeToken<? extends Throwable>>of());
}

</code></pre>

<pre class="type-3 type-10 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Executes methods or other tests from the same test unit">ExecutionTester</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
- Executes methods or other tests from the same test unit
"></span><br>
@Test(expectedExceptions=TestException.class) public void testPropagateExceptionThatsInList() throws Throwable {
  Exception e=new TestException();
  propagateIfPossible(e,ImmutableSet.<TypeToken<? extends Throwable>>of(typeToken(TestException.class)));
}

</code></pre>

<pre class="type-3 type-10 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Executes methods or other tests from the same test unit">ExecutionTester</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
- Executes methods or other tests from the same test unit
"></span><br>
@Test(expectedExceptions=IllegalArgumentException.class) public void testPropagateStandardExceptionIllegalArgumentException() throws Throwable {
  Exception e=new IllegalArgumentException();
  propagateIfPossible(new RuntimeException(e),ImmutableSet.<TypeToken<? extends Throwable>>of());
}

</code></pre>

<pre class="type-3 type-10 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Executes methods or other tests from the same test unit">ExecutionTester</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
- Executes methods or other tests from the same test unit
"></span><br>
@Test(expectedExceptions=IllegalStateException.class) public void testPropagateStandardExceptionIllegalStateExceptionNestedInHttpResponseException() throws Throwable {
  Exception e=new IllegalStateException();
  propagateIfPossible(new HttpResponseException("goo",createNiceMock(HttpCommand.class),null,e),ImmutableSet.<TypeToken<? extends Throwable>>of());
}

</code></pre>

<pre class="type-3 type-10 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Executes methods or other tests from the same test unit">ExecutionTester</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
- Executes methods or other tests from the same test unit
"></span><br>
@Test(expectedExceptions=HttpResponseException.class) public void testPropagateStandardExceptionHttpResponseException() throws Throwable {
  Exception e=new HttpResponseException("goo",createNiceMock(HttpCommand.class),null);
  propagateIfPossible(new RuntimeException(e),ImmutableSet.<TypeToken<? extends Throwable>>of());
}

</code></pre>

<pre class="type-3 type-10 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Executes methods or other tests from the same test unit">ExecutionTester</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
- Executes methods or other tests from the same test unit
"></span><br>
@Test(expectedExceptions=ResourceNotFoundException.class) public void testPropagateStandardExceptionResourceNotFoundException() throws Throwable {
  Exception e=new ResourceNotFoundException();
  propagateIfPossible(new RuntimeException(e),ImmutableSet.<TypeToken<? extends Throwable>>of());
}

</code></pre>

<pre class="type-3 type-10 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Executes methods or other tests from the same test unit">ExecutionTester</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
- Executes methods or other tests from the same test unit
"></span><br>
@Test(expectedExceptions=IllegalStateException.class) public void testPropagateStandardExceptionIllegalStateException() throws Throwable {
  Exception e=new IllegalStateException();
  propagateIfPossible(new RuntimeException(e),ImmutableSet.<TypeToken<? extends Throwable>>of());
}

</code></pre>

<pre class="type-3 type-10 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Executes methods or other tests from the same test unit">ExecutionTester</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
- Executes methods or other tests from the same test unit
"></span><br>
@Test(expectedExceptions=UnsupportedOperationException.class) public void testPropagateStandardExceptionUnsupportedOperationExceptionNestedInHttpResponseException() throws Throwable {
  Exception e=new UnsupportedOperationException();
  propagateIfPossible(new HttpResponseException("goo",createNiceMock(HttpCommand.class),null,e),ImmutableSet.<TypeToken<? extends Throwable>>of());
}

</code></pre>

<pre class="type-10 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Executes methods or other tests from the same test unit">ExecutionTester</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Executes methods or other tests from the same test unit
"></span><br>
@Test(expectedExceptions=AssertionError.class) public void testPropagateStandardExceptionAssertionError() throws Throwable {
  AssertionError e=new AssertionError();
  propagateIfPossible(new RuntimeException(e),ImmutableSet.<TypeToken<? extends Throwable>>of());
}

</code></pre>

<pre class="type-3 type-10 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Executes methods or other tests from the same test unit">ExecutionTester</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
- Executes methods or other tests from the same test unit
"></span><br>
@Test(expectedExceptions=IllegalArgumentException.class) public void testPropagateStandardExceptionIllegalArgumentExceptionNestedInHttpResponseException() throws Throwable {
  Exception e=new IllegalArgumentException();
  propagateIfPossible(new HttpResponseException("goo",createNiceMock(HttpCommand.class),null,e),ImmutableSet.<TypeToken<? extends Throwable>>of());
}

</code></pre>

<pre class="type-3 type-10 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Executes methods or other tests from the same test unit">ExecutionTester</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
- Executes methods or other tests from the same test unit
"></span><br>
@Test(expectedExceptions=AuthorizationException.class) public void testPropagateCreationExceptionAuthorizationException() throws Throwable {
  Exception e=new AuthorizationException();
  propagateIfPossible(new CreationException(ImmutableSet.of(new Message(ImmutableList.of(),"Error in custom provider",e))),ImmutableSet.<TypeToken<? extends Throwable>>of());
}

</code></pre>

<pre class="type-3 type-10 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Executes methods or other tests from the same test unit">ExecutionTester</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
- Executes methods or other tests from the same test unit
"></span><br>
@Test(expectedExceptions=TestException.class) public void testPropagateWrappedExceptionThatsInList() throws Throwable {
  Exception e=new TestException();
  propagateIfPossible(new RuntimeException(e),ImmutableSet.<TypeToken<? extends Throwable>>of(typeToken(TestException.class)));
}

</code></pre>

<script>$(document).ready(function() {
  $('pre code').each(function(i, block) {
    hljs.highlightBlock(block);
  });
});</script>
