<h3><span class=" glyphicon glyphicon-tag"/>&nbspUtilityVerifier</h3><kbd>Verifies (un)successful execution of the test case by reporting explicitly a failure</kbd><br><br><br><h4 style="margin:0px">Class: org.apache.abdera.test.parser.stax.ConcurrencyTest </h4><pre class="type-12 type-10 type-11 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies assertions in iterations">IterativeVerifier</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies assertions inside branch conditions">BranchVerifier</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies (un)successful execution of the test case by reporting explicitly a failure">UtilityVerifier</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies assertions in iterations
- Verifies assertions inside branch conditions
- Verifies (un)successful execution of the test case by reporting explicitly a failure
"></span><br>
/** 
 * Test for a concurrency issue that caused a ConcurrentModificationException in Abdera 0.1.0 but seems to be fixed
 * in 0.2. We leave the test here to prevent possible regressions.
 */
@Test public void testSetContentMT() throws Exception {
  Thread t[]=new Thread[N_THREADS];
  final boolean failed[]=new boolean[t.length];
  for (int i=0; i < t.length; ++i) {
    final int j=i;
    failed[i]=false;
    Runnable r=new Runnable(){
      public void run(){
        try {
          setContent();
        }
 catch (        Exception e) {
          e.printStackTrace();
          failed[j]=true;
          fail(e.toString());
        }
      }
    }
;
    t[i]=new Thread(r);
    t[i].start();
  }
  for (int i=0; i < t.length; ++i) {
    t[i].join();
    if (failed[i]) {
      fail("Thread " + t[i] + " failed.");
    }
  }
}

</code></pre>

<br>
<h4 style="margin:0px">Class: org.apache.axiom.om.ds.jaxb.JAXBOMDataSourceTest </h4><pre class="type-11 type-15 type-4 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies (un)successful execution of the test case by reporting explicitly a failure">UtilityVerifier</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies whether two objects/variables are the same">IdentityVerifier</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Contains more than 2 JUnit-based stereotypes">HybridVerifier</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies (un)successful execution of the test case by reporting explicitly a failure
- Verifies whether two objects/variables are the same
- Contains more than 2 JUnit-based stereotypes
"></span><br>
/** 
 * Tests that an {@link XMLStreamException} thrown by the {@link XMLStreamWriter} during
 * serialization is propagated without being wrapped. Note that this implies that the data must
 * unwrap {@link JAXBException} to extract the cause.
 */
@Test public void testExceptionDuringSerialization() throws Exception {
  OMFactory omFactory=OMAbstractFactory.getOMFactory();
  JAXBContext context=JAXBContext.newInstance(DocumentBean.class);
  DocumentBean object=new DocumentBean();
  object.setId("test");
  OMSourcedElement element=omFactory.createOMElement(new JAXBOMDataSource(context,object));
  XMLStreamException exception=new XMLStreamException("TEST");
  try {
    element.serialize(new ExceptionXMLStreamWriterWrapper(StAXUtils.createXMLStreamWriter(new ByteArrayOutputStream()),exception));
    fail("Expected XMLStreamException");
  }
 catch (  XMLStreamException ex) {
    assertSame(exception,ex);
  }
}

</code></pre>

<br>
<script>$(document).ready(function() {
  $('pre code').each(function(i, block) {
    hljs.highlightBlock(block);
  });
});</script>
