<h3 style="margin:0px">Class: org.apache.cassandra.concurrent.DebuggableScheduledThreadPoolExecutorTest (1 methods) </h3><br><pre style="padding:0"><code class="html"><div id="tags"><button id="15"style="border-width:0;padding:0;background:#282B2E"  onclick="filter('15')" data-toggle="tooltip" title="Verifies (un)successful execution of the test case by reporting explicitly a failure"><kbd id="tag-15"class="label-info"style="display: inline-block;font-size:7pt" >UtilityVerifier&nbsp;(1)</kbd></button>&nbsp;</div></code></pre><center><button onclick="showBlocks()" style="margin:6px">Update filter <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span> </button></center><br>
<pre class="type-15 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies (un)successful execution of the test case by reporting explicitly a failure">UtilityVerifier</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies (un)successful execution of the test case by reporting explicitly a failure
"></span><br>
@Test public void testShutdown() throws ExecutionException, InterruptedException, IOException {
  DebuggableScheduledThreadPoolExecutor testPool=new DebuggableScheduledThreadPoolExecutor("testpool");
  final AtomicInteger value=new AtomicInteger(0);
  ScheduledFuture future=testPool.schedule(new Runnable(){
    public void run(){
      value.incrementAndGet();
    }
  }
,1,TimeUnit.SECONDS);
  future.get();
  assert value.get() == 1;
  future=testPool.schedule(new Runnable(){
    public void run(){
      value.incrementAndGet();
    }
  }
,10,TimeUnit.SECONDS);
  StorageService.instance.drain();
  testPool.shutdown();
  future.get();
  assert value.get() == 2;
  future=testPool.schedule(new Runnable(){
    public void run(){
      value.incrementAndGet();
    }
  }
,1,TimeUnit.SECONDS);
  try {
    future.get(2,TimeUnit.SECONDS);
    Assert.fail("Task should be cancelled");
  }
 catch (  CancellationException e) {
  }
catch (  TimeoutException e) {
    Assert.fail("Task should be cancelled");
  }
  assert future.isCancelled();
  assert value.get() == 2;
}

</code></pre>

<script>$(document).ready(function() {
  $('pre code').each(function(i, block) {
    hljs.highlightBlock(block);
  });
});</script>
